name: ninjafood
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'



dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.5
  shared_preferences: ^2.0.18
  intl: 0.17.0
  http: ^0.13.5
  fpdart: ^0.5.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  image_picker: ^0.8.7
  firebase_core: ^2.8.0
  firebase_storage: ^11.0.16
  flutter_zoom_drawer: ^3.0.4+1
  font_awesome_flutter: ^10.4.0
  firebase_crashlytics: ^3.0.17
#  flutter_launcher_icons: ^0.12.0
  crypto: ^3.0.2
  google_sign_in: ^6.0.2
  #  sign_in_with_apple: ^4.3.0
  flutter_facebook_auth: ^5.0.8
  carousel_slider: ^4.2.1
  auto_animated: ^3.1.0
  flutter_typeahead: ^4.3.7
  cached_network_image: ^3.2.3
  firebase_messaging: ^14.4.0
  uuid: ^3.0.7
  tuple: ^2.0.1
  file_picker: ^4.2.0
  video_player: ^2.6.1
  permission_handler: ^10.2.0
  path_provider: ^2.0.14
  open_file: ^3.2.1
  flutter_html: ^2.2.0
  flutter_slidable: ^2.0.0



  ninja_theme:
#    git:
#      url: https://github.com/quocbao238/ninjafood_theme.git
#      ref: devMaster
    path: ../NinjaFood_Theme


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
